export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const CHANGE_NEW_TITLE = 'CHANGE_NEW_TITLE';
export const CHANGE_NEW_DESCR = 'CHANGE_NEW_DESCR';
export const CHANGE_NEW_IS_IMPORTANT = 'CHANGE_NEW_IS_DONE';
export const REMOVE_TASK = 'REMOVE_TASK';
export const IS_DONE_TOGGLE = 'IS_DONE_TOGGLE';